import "./globals.css";
import type { Metadata } from "next";
import { DM_Sans } from "next/font/google";
import SmoothScroller from "@/app/(root)/_components/smooth-scroller";
import { Toaster } from "sonner";
import TransitionProvider from "@/providers/transition-provider";

const dmSans = DM_Sans({
  variable: "--font-dm-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <body className={`${dmSans.variable} antialiased`}>
        <SmoothScroller />
        <TransitionProvider>{children}</TransitionProvider>
        <Toaster position="bottom-center" />
      </body>
    </html>
  );
}
